### ISSUE TITLE
V0.3.0 Causes Homebridge to Shut down

### ISSUE THREAD

**Issue by rcoletti116** [jimhe/homebridge-infinitude#17]
When I attempt to change the temperature under _Auto_ the I get an error "URL not defined" which causes Homebridge to crash. Logs:
[2020-4-14 12:31:08] ReferenceError: URL is not defined
at InfinitudeClient.setActivity (/usr/lib/node_modules/homebridge-infinitude/src/InfinitudeClient.js:121:17)
at InfinitudeThermostat.<anonymous> (/usr/lib/node_modules/homebridge-infinitude/src/InfinitudeThermostat.js:54:34)
at emitMany (events.js:147:13)
at Characteristic.emit (events.js:224:7)
at Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:882:22)
at Array.forEach (<anonymous>)
at Bridge.Accessory._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:822:8)
at emitMany (events.js:147:13)
at HAPServer.emit (events.js:224:7)
at HAPServer._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:974:10)
at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
at emitNone (events.js:106:13)
at IncomingMessage.emit (events.js:208:7)
at endReadableNT (_stream_readable.js:1064:12)
at _combinedTickCallback (internal/process/next_tick.js:139:11)
at process._tickCallback (internal/process/next_tick.js:181:9)
[2020-4-14 12:31:08] Got SIGTERM, shutting down Homebridge...
[2020-4-14 12:31:09] [InfinitudePlatform] http://10.0.1.141:3000/api/config/zones/zone/0/activities/activity/4?htsp=69.0
[2020-4-14 12:31:09] [InfinitudePlatform] http://10.0.1.141:3000/api/config/zones/zone/0/activities/activity/4?clsp=76.0
homebridge.service: main process exited, code=exited, status=143/n/a
Unit homebridge.service entered failed state.

**Comment by jimhe** [comment]
@rcoletti116 can you check if 0.3.1 fixes it?

**Comment by rcoletti116** [comment]
Yes, Homebridge no longer crashes.

**Comment by jimhe** [comment]
Good news. Please reopen if necessary.
