### ISSUE TITLE
Cannot read property 'htsp' of undefined...

### ISSUE THREAD

**Issue by kskenyon** [jimhe/homebridge-infinitude#19]
(node:369) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'htsp' of undefined
    at InfinitudeThermostat.<anonymous> (/homebridge/node_modules/homebridge-infinitude/src/InfinitudeThermostat.js:129:82)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:369) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:369) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'htsp' of undefined
    at InfinitudeThermostat.<anonymous> (/homebridge/node_modules/homebridge-infinitude/src/InfinitudeThermostat.js:129:82)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:369) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

Any idea what is missing?  I'm running inside a docker image of homebridge-config-ui-x.

Infinitude seems to be working correctly.

Kevin

**Comment by rcoletti116** [comment]
Check out #3. 

If it’s the same issue (logs are the same), this had to do with schedules and profiles. Assuming you’re on the latest version, leave your thermostat on manual and build your automations in HomeKit. Remove any schedule from the thermostat so it doesn’t fall back.

**Comment by kskenyon** [comment]
I went back and read the other thread.  Your suggestion doesn't meet the WAF requirement.  She won't use Homekit to change schedules.  This plugin isn't helpful if it requires messing with the thermostat.  It took long enough to get her switched over from the old round Honeywell.  We still argue about the schedule and auto functions.  Auto is a difficult concept apparently.

I just suggest that this plugin could use some fine tuning before it's ready for prime time.  It should just work with the thermostat settings that are normally used.  It doesn't do that yet.

Kevin

**Comment by rcoletti116** [comment]
I won’t weigh in on whether it’s ready for prime-time. If you’re using homebridge, you’re a tinkerer. I get it though, my wife isn’t technical and just expects things to work, so our tinkering has to be usable for normal human interaction. I was just providing some direction on how to make your error go away. 

This plugin is working well for me these days and we never have to touch the thermostats. 
I’ve got a general schedule, and some HomeKit scenes for Climate Home, Climate Away, Climate Sleep, etc... I leave the house and it switches to Away. 11:00pm, Sleep. I have a native HomeKit thermostat as well and use the same automations. Unfortunately with HomeKit the thermostats are maybe a little less sophisticated/complicated than the Infinity in terms of profiles, but I like how I’ve got it working in HomeKit.

The plugin developer has said he’s open to feedback and requests, so once he sees this he may ask you more about how you’d like to use it.

**Comment by jlg89** [comment]
Same issue here. If the t-stat has no schedules defined and is set to "hold" or "off," this error doesn't occur, but I  still run into odd issues with the t-stat settings changing with no explanation as to why. I won't complain about a free module that does actually have good functionality, and even my HVAC guy is impressed with what I'm able to do with this module and the infinitude daemon. From the standpoint of constructive criticism, though, I have two suggestions:

1. The plugin should handle this (seemingly common) error gracefully, without affecting the overall operation of the homebridge instance. Maybe it already does that, but it seems to make problems on my system.

2. It would be very preferable if the plugin could work with the "native" t-stat settings, at least insofar as they're available via infinitude. My t-stat does not appear to have the ability to delete schedules once they're created--they can be edited, but not removed. Surely there's a way, but it's proving a challenge even for me, the tinkerer (tried using infinitude to do it; doesn't work). Also, as Kevin mentioned, the tinkerer is seldom the only one using the t-stat. Since the t-stat has good scheduling tools already, why reinvent the wheel, and why force everyone to use the homebridge interface? The same basic functionality should be available whether one is using the MyInfinity app or infinitude; you shouldn't be able to effectively disable one via the other. That's a recipe for domestic disturbance.

**Comment by jlg89** [comment]
Another reason to support working with a t-stat with schedules enabled: The t-stats use the built-in schedule to trigger other useful things like backlighting level changes (e.g. dim to 20% during Sleep, brighten to 100% during Wake & Home).

**Comment by dotfortun3-code** [comment]
> 
> 
> Another reason to support working with a t-stat with schedules enabled: The t-stats use the built-in schedule to trigger other useful things like backlighting level changes (e.g. dim to 20% during Sleep, brighten to 100% during Wake & Home).

I forked this project and modified it to work with schedules, it sets the current scheduled activities temperature, so if you adjust the temp while it is in the "Home" mode, it will keep that temperature whenever it is in the "Home" mode.

It also uses Auto, Cool, Heat and Off, and matched the Infinity T-stat with the mode you select. There is an option to have the Off mode set the system to Away and either hold it indefinitely, or to the next scheduled activity

**Comment by rcoletti116** [comment]
@dotfortun3-code I'm curious which version you started from? I have not gotten the chance to test yet, but assuming that your changes can work with or without a schedule (allowing Automations to done in HomeKit by Geo or Time) why not make a PR?

**Comment by dotfortun3-code** [comment]
@rcoletti116 I forked from the latest version. It should work with automations in HomeKit.

I haven't ever really contributed to a GitHub repo before so I was not sure what the best practice is. I would absolutely submit a PR, if you think that it's good. Just let me know and what changes need to happen to make it merge better.
