### ISSUE TITLE
Getting multiple errors and I am unable to see the correct temperature or set the temperature in the home app

### ISSUE THREAD

**Issue by jarboer** [jimhe/homebridge-infinitude#29]
Hi, I'm hoping someone can help me out. I'm having issues getting the homebridge-infinitude plugin to work. I'm running Hombridge and infinitude on my Rasberry Pi zero, and I access infinitude from localhost to use it with the plugin. I can get and send data just fine to infinitude through a browser but using the plugin always results in an error. I'm getting consistently getting errors like these:
`[02/03/2021, 00:35:53] [homebridge-infinitude] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number -7.222222222222222 exceeded minimum of 0. See https://git.io/JtMGR for more info.`

`[02/03/2021, 00:35:53] [homebridge-infinitude] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: number -5 exceeded minimum of 10. See https://git.io/JtMGR for more info.`

Which I think might be caused by conversion from Celsius to Fahrenheit, I use celcius since I live in Canada, so I think the conversion is messing things up. My infinitude data received from my thermostat is in celsius so the conversion is probably causing issues. The temperature in the Home app is wrong, it's always around -5.

I'm also getting an error when trying to change the temperature in the Home app, like this:
[02/03/2021, 00:49:35] [InfinitudePlatform] http://127.0.0.1:3000/api/config/zones/zone/0?holdActivity=manual&hold=on
[02/03/2021, 00:49:40] [InfinitudePlatform] Error: timeout of 5000ms exceeded
    at createError (/usr/local/lib/node_modules/homebridge-infinitude/node_modules/axios/lib/core/createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (/usr/local/lib/node_modules/homebridge-infinitude/node_modules/axios/lib/adapters/http.js:217:16)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  config: {
    adapter: [Function: httpAdapter],
    transformRequest: { '0': [Function: transformRequest] },
    transformResponse: { '0': [Function: transformResponse] },
    timeout: 5000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.18.1'
    },
    method: 'get',
    url: 'http://127.0.0.1:3000/systems.json',
    data: undefined
  },
  code: 'ECONNABORTED',
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      protocol: 'http:',
      maxRedirects: 21,
      maxBodyLength: 10485760,
      path: '/systems.json',
      method: 'get',
      headers: [Object],
      agent: undefined,
      auth: undefined,
      hostname: '127.0.0.1',
      port: '3000',
      nativeProtocols: [Object],
      pathname: '/systems.json'
    },
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      _header: 'GET /systems.json HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.18.1\r\n' +
        'Host: 127.0.0.1:3000\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/systems.json',
      _ended: false,
      res: null,
      aborted: true,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      host: '127.0.0.1',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://127.0.0.1:3000/systems.json',
    [Symbol(kCapture)]: false
  },
  response: undefined
}

**Comment by dotfortun3-code** [comment]
Did you try using my version of the plugin? This one is no longer maintained, but this version should handle Celsius.

https://github.com/dotfortun3-code/homebridge-infinitude-v2
