### ISSUE TITLE
Unable to load plugin

### ISSUE THREAD

**Issue by ansuz07** [jimhe/homebridge-infinitude#4]
Just started getting this error:

[10/27/2019, 11:24:46 AM] [InfinitudePlatform] TypeError: Cannot read property 'arrayMode' of undefined

    at Object.convertToJson (/homebridge/node_modules/homebridge-infinitude/node_modules/fast-xml-parser/src/node2json.js:24:43)

    at refresh.response (/homebridge/node_modules/homebridge-infinitude/src/InfinitudeClient.js:51:26)

    at InfinitudeClient.<anonymous> (/homebridge/node_modules/homebridge-infinitude/src/InfinitudeClient.js:38:38)

    at process._tickCallback (internal/process/next_tick.js:68:7)

Any advice?

**Comment by kskenyon** [comment]
I'm getting the same error.  Fresh installation.

**Comment by ansuz07** [comment]
I honestly just gave up on it and moved to Hass.io

**Comment by rcoletti116** [comment]
Same. It was working and stopped working after a recent update, but I haven't been able to identify what caused it. Maybe a node update.

[InfinitudePlatform] TypeError: Cannot read property 'arrayMode' of undefined
at Object.convertToJson (/usr/lib/node_modules/homebridge-infinitude/node_modules/fast-xml-parser/src/node2json.js:24:43)
at refresh.response (/usr/lib/node_modules/homebridge-infinitude/src/InfinitudeClient.js:51:26)
at InfinitudeClient.<anonymous> (/usr/lib/node_modules/homebridge-infinitude/src/InfinitudeClient.js:38:38)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by swerb73** [comment]
Hmm, I just installed the update that came out today and am getting this problem as well?

**Comment by rcoletti116** [comment]
> Hmm, I just installed the update that came out today and am getting this problem as well?

You only updated the homebridge-infinitude plugin?

It's been broken for me for months and I haven't found a way to resolve. It's also seen no development. The original developer has stated he did not realize others were using it.

**Comment by ansuz07** [comment]
Yeah - I gave up on this plugin months ago and moved to Hass.io

**Comment by swerb73** [comment]
I couldn't even get it installed before this update, now it's installed and I get this error.

Hass.io, is that full Home Assistant?

**Comment by ansuz07** [comment]
Yes - home assistant. There is a plug-in you can download that works.

**Comment by swerb73** [comment]
Got it, trying to avoid moving everything to homeassistant. I use homebridge just to get iOS/Home support for my smartthings integration...  I have infinitude thermostats published from a custom smartthings I did, they just aren't great so was hoping this would be better...

**Comment by jimhe** [comment]
Sorry for the delay. I finally got around to tending to this plugin. It has been fixed in ca250a2fc3e603533f20d07a8d4c419d5595f340
